splash = false
wallpaper {
  monitor = desc:ASUSTek COMPUTER INC XG27UCG T1LMQS062570
  path = /home/chan/xdg/Pictures/mountain_creek_upper.jpg
}

wallpaper {
  monitor = desc:ASUSTek COMPUTER INC XG27UCG T2LMQS006671
  path = /home/chan/xdg/Pictures/mountain_creek_lower.jpg
}
